### ISSUE TITLE
Porto theme Mega Menu

### ISSUE THREAD

**Issue by devdesco-ceo** [mirasvit/module-blog#8]
Can you please add checks for menu injection for a case when custom Mega Menu is active?
On my Porto theme Mega Menu the links are not showing up.

**Comment by adrok** [comment]
Smartwave_MegaMenu not implement native M2 menu observers/events, that's why we can't add our link to this menu.

But you can use custom block for add new/custom links:
![image](https://cloud.githubusercontent.com/assets/1307119/14018119/96e6b0a6-f1d4-11e5-9013-9cc11be85797.png)
![image](https://cloud.githubusercontent.com/assets/1307119/14018125/a0fff3cc-f1d4-11e5-81d6-0a5510d8c78e.png)

**Comment by devdesco-ceo** [comment]
Yes, that's what I ended up with.
